data:
  filepath: '../data/dataset/normal/mnist.pkl'
  normalize: false
  standardize: true
  batch_size: 256

model:
  arch: "a" # options: a,b,c
  epochs: 50
  early_stopping: false
optimizer:
  momentum: 0
  l2_penalty: 0.0001
  lr: 0.1
